[package]
name = "wdn-build"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "wdn-build"
test = false
doctest = false

[dependencies]
image = { version = "0.25.9", default-features = false, features = ["png"] }
