[package]
name = "wdn-tasks"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0-rc.1", default-features = false }
wdn-physics = { version = "0.1.0", path = "../wdn-physics" }
