[package]
name = "wdn-world"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = "0.18.0-rc.1"
bevy_ecs = "0.18.0-rc.1"
bevy_math = "0.18.0-rc.0"
bevy_time = "0.18.0-rc.0"
bevy_transform = "0.18.0-rc.1"
wdn-physics = { version = "0.1.0", path = "../wdn-physics" }
